version: '3.8'

services:
  # MongoDB Database
  mongodb:
    image: mongo:6.0
    container_name: financial-hub-db
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: financial-hub
    volumes:
      - mongodb_data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    ports:
      - "27017:27017"
    networks:
      - financial-hub-network

  # Backend API
  backend:
    build: ./backend
    container_name: financial-hub-backend
    restart: unless-stopped
    environment:
      NODE_ENV: production
      PORT: 5000
      MONGODB_URI: mongodb://admin:password@mongodb:27017/financial-hub?authSource=admin
      JWT_SECRET: your-super-secret-jwt-key-change-this-in-production
      JWT_EXPIRE: 30d
      FRONTEND_URL: http://localhost:3000
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    networks:
      - financial-hub-network
    volumes:
      - ./backend:/app
      - /app/node_modules

  # Frontend Application
  frontend:
    build: ./frontend
    container_name: financial-hub-frontend
    restart: unless-stopped
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - financial-hub-network

  # Redis for session storage (optional)
  redis:
    image: redis:7-alpine
    container_name: financial-hub-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - financial-hub-network
    volumes:
      - redis_data:/data

volumes:
  mongodb_data:
  redis_data:

networks:
  financial-hub-network:
    driver: bridge
