import React from 'react';
import { Link } from 'react-router-dom';

const LAST_UPDATED = 'August 26, 2026';

const Section = ({ title, children }) => (
  <section className="mb-8">
    <h2 className="text-lg font-semibold text-gray-900 mb-3">{title}</h2>
    <div className="space-y-3 text-sm text-gray-700 leading-relaxed">{children}</div>
  </section>
);

const Terms = () => {
  return (
    <div className="min-h-screen bg-gray-50 py-12 px-4 sm:px-6 lg:px-8">
      <div className="max-w-3xl mx-auto bg-white shadow rounded-lg p-8 sm:p-10">
        <Link to="/" className="text-sm text-primary-600 hover:text-primary-700">&larr; Back to Race-OS</Link>

        <h1 className="text-2xl font-bold text-gray-900 mt-4 mb-1">Terms of Service</h1>
        <p className="text-sm text-gray-500 mb-8">Last updated: {LAST_UPDATED}</p>

        <div className="mb-8 p-4 bg-amber-50 border border-amber-200 rounded-md text-sm text-amber-800">
          <strong>Note:</strong> Race OS is currently operated by an individual, not a registered
          company. This draft was written to accurately describe what Race OS actually does, but it
          has not been reviewed by a lawyer - have one review it before this is relied on for real
          users, especially given it covers financial and tax-adjacent data.
        </div>

        <Section title="1. Acceptance of These Terms">
          <p>
            These Terms of Service ("Terms") govern your access to and use of Race OS (the "Service"),
            operated by Race OS ("we," "us," or "our"). By creating an account or using the Service,
            you agree to be bound by these Terms. If you do not agree, do not use the Service.
          </p>
        </Section>

        <Section title="2. What Race-OS Is">
          <p>
            Race-OS is a financial dashboard for creators and freelancers. It helps you track income
            and expenses, generate invoices, estimate taxes, and optionally connect bank accounts or
            creator platforms (YouTube, Twitch, Patreon) to automatically import financial data.
          </p>
          <p>
            Race-OS is a tool to help you organize and estimate your finances. It is not a bank,
            a payment processor, a licensed tax preparer, or a registered investment or financial
            advisor.
          </p>
        </Section>

        <Section title="3. Not Financial, Tax, or Legal Advice">
          <p>
            <strong>
              All tax estimates, deduction suggestions, categorizations, and financial summaries
              provided by Race-OS - including anything labeled "AI-powered" or "forecast" - are
              informational estimates only.
            </strong>{' '}
            They are generated by automated calculations and heuristics, not reviewed by a licensed
            professional, and may be inaccurate or incomplete. They are not a substitute for advice
            from a qualified accountant, tax preparer, or financial advisor. You are solely
            responsible for verifying your own tax filings and financial decisions, and for consulting
            a licensed professional before relying on anything the Service tells you.
          </p>
        </Section>

        <Section title="4. Accounts">
          <p>
            Account creation and sign-in are handled by our authentication provider, Clerk. You're
            responsible for keeping your account credentials secure and for all activity that happens
            under your account. You must be at least 18 years old to use the Service.
          </p>
        </Section>

        <Section title="5. Connecting Third-Party Services">
          <p>
            Race-OS lets you optionally connect third-party services to import your financial data:
          </p>
          <ul className="list-disc pl-5 space-y-1">
            <li><strong>Bank accounts</strong>, via Plaid</li>
            <li><strong>YouTube, Twitch, and Patreon</strong>, via each platform's own OAuth sign-in</li>
          </ul>
          <p>
            When you connect one of these, you're authorizing Race-OS to access the relevant account
            data on your behalf, subject to that provider's own terms and privacy policy as well as
            ours. We don't control these third-party services and aren't responsible for their
            availability, accuracy, or any changes they make. You can disconnect any of these at any
            time from within the Service.
          </p>
          <p>
            You may also upload your own bank statement files (CSV) as an alternative to connecting a
            bank account directly.
          </p>
        </Section>

        <Section title="6. Acceptable Use">
          <p>You agree not to:</p>
          <ul className="list-disc pl-5 space-y-1">
            <li>Use the Service for any unlawful purpose, or to submit fraudulent financial or tax information</li>
            <li>Attempt to access another user's account or data without authorization</li>
            <li>Probe, scan, or attempt to bypass the Service's security or rate limits</li>
            <li>Use the Service to process another person's financial data without their consent</li>
            <li>Reverse-engineer or resell the Service without our written permission</li>
          </ul>
        </Section>

        <Section title="7. Fees">
          <p>
            Race OS is currently offered free of charge. We may introduce paid plans in the future;
            if we do, you'll be notified and given the chance to review pricing before being charged.
          </p>
        </Section>

        <Section title="8. Your Content">
          <p>
            You retain ownership of the financial data, invoices, client information, and other
            content you upload or create in Race-OS ("Your Content"). You grant us a limited license
            to store, process, and display Your Content solely to operate and improve the Service for
            you. We do not sell Your Content.
          </p>
        </Section>

        <Section title="9. Termination">
          <p>
            You may stop using the Service and request account deletion at any time by contacting us
            at hello@raceos.me. We may suspend or terminate access to the Service if you violate these
            Terms, engage in fraudulent activity, or if required by law.
          </p>
        </Section>

        <Section title="10. Disclaimer of Warranties">
          <p>
            THE SERVICE IS PROVIDED "AS IS" AND "AS AVAILABLE," WITHOUT WARRANTIES OF ANY KIND, EXPRESS
            OR IMPLIED, INCLUDING WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, OR
            ACCURACY OF ANY FINANCIAL OR TAX CALCULATIONS. WE DO NOT GUARANTEE THE SERVICE WILL BE
            UNINTERRUPTED, ERROR-FREE, OR THAT ANY DATA SYNCED FROM THIRD-PARTY SERVICES WILL BE
            ACCURATE OR COMPLETE.
          </p>
        </Section>

        <Section title="11. Limitation of Liability">
          <p>
            TO THE MAXIMUM EXTENT PERMITTED BY LAW, RACE OS WILL NOT BE LIABLE FOR
            ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES, OR ANY LOSS OF
            PROFITS, DATA, OR BUSINESS ARISING FROM YOUR USE OF THE SERVICE - INCLUDING DECISIONS MADE
            BASED ON TAX ESTIMATES OR CATEGORIZATIONS THE SERVICE PROVIDES. OUR TOTAL LIABILITY FOR ANY
            CLAIM RELATED TO THE SERVICE WILL NOT EXCEED THE AMOUNT YOU PAID US, IF ANY, IN THE 12
            MONTHS BEFORE THE CLAIM AROSE.
          </p>
        </Section>

        <Section title="12. Changes to These Terms">
          <p>
            We may update these Terms from time to time. If we make material changes, we'll notify you
            (for example, by email or an in-app notice) before they take effect. Continuing to use the
            Service after changes take effect means you accept the updated Terms.
          </p>
        </Section>

        <Section title="13. Governing Law">
          <p>
            These Terms are governed by the laws of Maharashtra, India, without regard to its
            conflict-of-law principles.
          </p>
        </Section>

        <Section title="14. Contact">
          <p>Questions about these Terms? Contact us at hello@raceos.me.</p>
        </Section>
      </div>
    </div>
  );
};

export default Terms;
